<a href="https://colab.research.google.com/github/2215151050haque/Simulation_Lab/blob/main/Assignment-2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import numpy as np

# With a fixed seed
np.random.seed(10)
matrix_fixed_seed = np.random.randint(1, 51, size=(3, 3))
print("Matrix with fixed seed:\n", matrix_fixed_seed)

# Without setting a seed
matrix_no_seed = np.random.randint(1, 51, size=(3, 3))
print("\nMatrix without seed:\n", matrix_no_seed)


Matrix with fixed seed:
 [[10 37 16]
 [ 1 50 29]
 [26 30 49]]

Matrix without seed:
 [[30 50  9]
 [10  1 43]
 [41 37 17]]


In [ ]:
# With a fixed seed
The matrices will generate same sequence of number each time executed.
This is useful for reproducibility.

# Without setting a seed
The number of the matrices will vary each time. The generated random numbers will be unpredictable every time.